server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        #注册进eureka中
  instance:
    prefer-ip-address: true         #以真实ip注册

spring:
  application:
    name: TIK-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver         #mysql 8.0以后版本的，与之前的有所不同
    url: jdbc:mysql:///website-comment?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:xiongjunmiao/top/Website/mapper/*Mapper.xml        #mapper文件的位置
  type-aliases-package: xiongjunmiao.top.Website.domain,xiongjunmiao.top.Website.query      #将别名配置进mybatis在写mapper的时候就用别名就可以

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /admin/login
      - /admin/register
      - /admin/info.
      - /product/**

logging:
  level:
    xiongjunmiao.top.Website: debug           #日志记录的级别
    #file: D:/xxxxxx.xxx      #将日志记录再那个文件里面
    #pattern:
    #file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ==== [%thread] ====  %-5level  %logger{50} - %msg%n"       #日志打印的格式