server:
  port: 6001
  #servlet:
    #context-path: /redis  #请求路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        #注册进eureka中
  instance:
    prefer-ip-address: true         #以真实ip注册

spring:
  application:
    name: REDIS-SERVICE
    redis:
      # redis数据库索引
      database: 0
      # redis ip
      host: localhost
      # redis 端口
      port: 6379
      #   host: 60.168.131.134
      #   port: 16379
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间 30秒（使用负值表示没有限制）
        max-wait: 30000
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接超时时间 30秒
        timeout: 30000
    #      password: woniu@red@092
    # redisson 锁
    lock:
      address: redis://localhost:6379
      database: 0
    jackson:
      # 北京时区
      time-zone: GMT+8
    http:
      multipart:
        # 文件上传最大大小
        maxFileSize: 50Mb
        # request 请求最大大小
        maxRequestSize: 80Mb

logging:
  level:
    xiongjunmiao.top.Website: debug           #日志记录的级别
    #file: D:/xxxxxx.xxx      #将日志记录再那个文件里面
    #pattern:
    #file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ==== [%thread] ====  %-5level  %logger{50} - %msg%n"       #日志打印的格式

