server:
  port: 8761


spring:
  application:
    name: EUREKA-SERVER

eureka:
  instance:
    hostname: localhost      #主机名
    prefer-ip-address: true     #客户端使用ip进行服务列表注册
  client:
    registerWithEureka: false    #是否要注册到eureka中
    fetchRegistry: false        #是否从eurek server获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
